### POST request to add a patient
POST http://localhost:4000/patients
Content-Type: application/json


{
  "name": "Yaodh",
  "email": "abqcc@gmail.com",
  "address": "123 main street",
  "dateOfBirth": "1994-08-04",
  "registeredDate": "2004-11-28"

}

###